package com.bill.billingsystem.Activity;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.GridLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.annotation.SuppressLint;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.database.Cursor;
import android.os.Bundle;

import com.bill.billingsystem.DataBase.DataBaseHandler;
import com.bill.billingsystem.R;
import com.bill.billingsystem.model.OnPdfFileSelectListener;
import com.bill.billingsystem.model.PdfAdapter;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecentInvoiceActivity extends AppCompatActivity implements OnPdfFileSelectListener {

    private DataBaseHandler db = new DataBaseHandler(this);
    String SHARED_PREFS = "shared_prefs";
    String USER_KEY = "user_key";
    String SPuser;
    public List<String> mPbillno = new ArrayList();

    public List<String> mPtamount = new ArrayList();
    public List<String> mPDate = new ArrayList();
    public List<String> mPtime = new ArrayList();
    public List<String> mPusername = new ArrayList();

    SharedPreferences sharedpreferences;

    private PdfAdapter pdfAdapter;
    private List<File> pdfList;

    private RecyclerView recyclerView;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_recent_invoice);
        sharedpreferences= getSharedPreferences(SHARED_PREFS, Context.MODE_PRIVATE);

        SPuser = sharedpreferences.getString(USER_KEY,null);

        System.out.println(SPuser);
        displayPdf();
    }

    public ArrayList<File> findPdf(File file){
        ArrayList<File> arrayList=new ArrayList<>();
        File[] files=file.listFiles();

        for (File singleFile:files){
            if(singleFile.isDirectory()&&!singleFile.isHidden()){
                arrayList.addAll(findPdf(singleFile));
            }
            else {
                if(singleFile.getName().endsWith(".pdf")){
                    arrayList.add(singleFile);
                }
            }
        }
        return arrayList;
    }
    private void displayPdf(){
        recyclerView=findViewById(R.id.recycler_view);
        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new GridLayoutManager(this,1));
        pdfList=new ArrayList<>();
        Cursor c1;
        if (SPuser.equals("admin")) {
            c1 = db.get_value("SELECT * FROM (SELECT * FROM Transation GROUP BY cus_id ) AS sorted ORDER BY time DESC LIMIT 10");
        }
        else {
            c1 = db.get_value("SELECT * FROM (SELECT * FROM Transation WHERE sales_user="+"'"+SPuser+"' GROUP BY cus_id) AS sorted ORDER BY time DESC LIMIT 10");
        }

        if (c1.moveToFirst()) {
            do {
                @SuppressLint("Range") String path = c1.getString(c1.getColumnIndex("file_Path"));
                @SuppressLint("Range") String data1 = c1.getString(c1.getColumnIndex("Bill_No"));
                @SuppressLint("Range") String data2 = c1.getString(c1.getColumnIndex("tamount"));

                @SuppressLint("Range") Long data3 = c1.getLong(c1.getColumnIndex("time"));

                @SuppressLint("Range") String data4 = c1.getString(c1.getColumnIndex("sales_user"));

                File file=new File(path);
                if(file.exists()){

                    SimpleDateFormat formatter = new SimpleDateFormat("HH:mm");


                    SimpleDateFormat formatter1 = new SimpleDateFormat("dd/MM/yyyy");
                    Date res = new Date(data3);

                    mPbillno.add("Bill No: "+data1);
                    mPtamount.add("Total Amount: "+data2+" Rs.");
                    mPtime.add("Time:"+formatter.format(res));
                    mPDate.add("Generated Date : "+formatter1.format(res));
                    mPusername.add("Generated BY: "+data4);
                    pdfList.add(file);
                }
            } while (c1.moveToNext());
        }
        pdfAdapter=new PdfAdapter(this,pdfList,this,mPbillno,mPtamount,mPDate,mPusername,mPtime);
        recyclerView.setAdapter(pdfAdapter);
    }

    @Override
    public void onpdfSelected(File file) {
        Intent i=new Intent(RecentInvoiceActivity.this,DocmentActivity.class);
        i.putExtra("path",file.getAbsolutePath());
        startActivity(i);
    }
}